"""Add reward fields to Mission

Revision ID: b492a3119c33
Revises: 99dc38601214
Create Date: 2024-12-11 14:44:55.563702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b492a3119c33'
down_revision = '99dc38601214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_strength', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reward_popularity', sa.Integer(), nullable=True))
        batch_op.drop_column('reward')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('reward_popularity')
        batch_op.drop_column('reward_strength')

    # ### end Alembic commands ###
