"""Add reward fields to Mission

Revision ID: e599c94b791c
Revises: 459bf751c3e2
Create Date: 2024-12-06 13:39:18.072963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e599c94b791c'
down_revision = '459bf751c3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
